name: Simple Pipeline

on:
  push:  # Trigger on any push to any branch
  workflow_dispatch:  # Adds a "Run workflow" button in the Actions tab
    inputs:
      username:
        description: 'Your name'
        required: false
        default: 'Guest'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Greet user
        run: echo "Hello, ${{ github.event.inputs.username }}!"