name: Simple Pipeline

on:
  push:  # This triggers on push to any branch

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, world!"